name: docker tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Test container images
      run: |
        docker pull shiftleft/scan-slim:latest
        docker pull shiftleft/scan:latest
        docker save -o scanslim.tar shiftleft/scan-slim:latest
        docker save -o scan.tar shiftleft/scan:latest
        docker run --rm -e "WORKSPACE=${PWD}" -v $PWD:/app shiftleft/scan:docker scan --src /app/scanslim.tar -o /app/reports --type docker
        docker run --rm -e "WORKSPACE=${PWD}" -e "FETCH_LICENSE=true" -e "ENABLE_OSS_RISK=true" -v $PWD:/app shiftleft/scan:docker scan --src /app/scan.tar -o /app/reports --type docker
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
